#lang racket/base

;;; Graph Generator
;;; Generates DOT/GraphViz graphs for dependency visualization

(require racket/contract
         racket/match
         racket/list
         racket/string
         racket/hash
         racket/port)

(provide generate-dependency-graph
         generate-execution-dag
         generate-layer-flow
         graph->dot
         save-dot-file
         render-graph)

;; Generate DOT format dependency graph
(define/contract (generate-dependency-graph symbols)
  (-> (listof any/c) string?)

  (define nodes
    (for/list ([sym symbols])
      (if (hash? sym)
          (format "  \"~a\" [label=\"~a\\n(~a)\"];"
                  (hash-ref sym 'name "unknown")
                  (hash-ref sym 'name "unknown")
                  (hash-ref sym 'type "unknown"))
          "")))

  (define edges
    (for/list ([sym symbols])
      (if (and (hash? sym) (hash-has-key? sym 'depends-on))
          (let ([name (hash-ref sym 'name "")]
                [deps (hash-ref sym 'depends-on '())])
            (define dep-list (if (list? deps) deps (list deps)))
            (string-join
             (for/list ([dep dep-list])
               (format "  \"~a\" -> \"~a\";" dep name))
             "\n"))
          "")))

  (format "digraph DependencyGraph {\n  rankdir=LR;\n  node [shape=box];\n\n~a\n\n~a\n}\n"
          (string-join nodes "\n")
          (string-join (filter non-empty-string? edges) "\n")))

;; Generate execution DAG
(define/contract (generate-execution-dag trace-data)
  (-> hash? string?)

  (define layers '(manifest parser orchestrator symbolic injector wordpress))

  (define nodes
    (for/list ([layer layers])
      (format "  \"~a\" [shape=box,style=filled,color=lightblue];" layer)))

  (define edges
    (for/list ([i (in-range (- (length layers) 1))])
      (format "  \"~a\" -> \"~a\";"
              (list-ref layers i)
              (list-ref layers (+ i 1)))))

  (format "digraph ExecutionDAG {\n  rankdir=TB;\n\n~a\n\n~a\n}\n"
          (string-join nodes "\n")
          (string-join edges "\n")))

;; Generate layer flow diagram
(define/contract (generate-layer-flow context-flow)
  (-> hash? string?)

  (define layers (hash-keys context-flow))

  (define nodes
    (for/list ([layer layers])
      (format "  \"~a\" [shape=box];" layer)))

  (define edges
    (for/list ([i (in-range (- (length layers) 1))])
      (format "  \"~a\" -> \"~a\";"
              (list-ref layers i)
              (list-ref layers (+ i 1)))))

  (format "digraph LayerFlow {\n  rankdir=LR;\n\n~a\n\n~a\n}\n"
          (string-join nodes "\n")
          (string-join edges "\n")))

;; Convert graph structure to DOT format
(define/contract (graph->dot graph-data #:title [title "Graph"])
  (->* (hash?) (#:title string?) string?)

  (format "digraph ~a {\n  label=\"~a\";\n  // Generated by WP Praxis Introspection\n}\n"
          (string-replace title " " "_")
          title))

;; Save DOT file
(define/contract (save-dot-file dot-string path)
  (-> string? path-string? void?)

  (call-with-output-file path
    #:exists 'replace
    (λ (out)
      (display dot-string out))))

;; Render graph using GraphViz (if available)
(define/contract (render-graph dot-string output-path [format "png"])
  (->* (string? path-string?) (string?) boolean?)

  (with-handlers ([exn:fail? (λ (e) #f)])
    (define dot-file (format "~a.dot" output-path))
    (save-dot-file dot-string dot-file)

    ;; Try to execute dot command
    (system (format "dot -T~a ~a -o ~a.~a" format dot-file output-path format))
    #t))

(define (non-empty-string? s)
  (and (string? s) (not (string=? s ""))))
